import Head from 'next/head'
import { signOut, useSession, getSession } from 'next-auth/react'

export default function Home() {
  const { data: session } = useSession()
  return (
    <div className='flex items-center justify-center w-screen h-screen'>
      <Head>
        <title>TheLoopers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='space-y-2'>
        <div className='relative w-20 h-20 '>
          <img src={session.user.image} alt="" className='rounded-full' />
        </div>
        <div className='text-2xl font-bold text-black'>Welcome {session.user.name}</div>
        <div>your email {session.user.email}</div>
        <div>
          <button className='p-3 text-xl font-semibold bg-red-500 rounded-md hover:bg-red-500/80' onClick={() => signOut()}>
            sign out
          </button>
        </div>
      </div>
    </div>
  )
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        destination: '/home',
        permanent: false,
      }
    }
  }
  return {
    props: {
      session,
    },
  }
}
